
# docker-compose.yml
version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: starpets-gg
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NUXT_PUBLIC_API_URL=${NUXT_PUBLIC_API_URL}
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "wget", "--spider", "http://localhost:3000"]
    #   interval: 30s
    #   retries: 3